### ISSUE TITLE
doesn't work in rails 4.1 and 4.2, undefined method `link_to_function'

### ISSUE THREAD

**Issue by francescob** [thoughtbot/paul_revere#29]
the announcement partial still uses `link_to_function' which was removed since version 4.1 (i guess, not sure about that)

**Comment by mjankowski** [comment]
Good catch -- apparently there's no test coverage on that view partial.  I'll check it out.

**Comment by mjankowski** [comment]
I just pushed a version 1.4 which I believe resolves this.

**Comment by francescob** [comment]
i confirm it's working on rails 4.2 now, thanks for the super fast update

**Comment by nasirvq** [comment]
It doesn't seem to be working in Rails 4.2.1?

**Comment by mjankowski** [comment]
Can you confirm that you are using the latest gem version?  What issue do you see?

**Comment by francescob** [comment]
It works with 4.2.1
One problem maybe that an helper called announcement_hidden? was renamed. I had a view using that and it was obviously broken. The right helper to use now is announcment_visible?
I hope this can help

**Comment by mjankowski** [comment]
That's correct -- the bump from 1.4 to 2.0.0 introduced some breaking changes (hence the major version bump).

Sounds like it's all sorted out.
